Failure case Handling
chargebee/chargebee-ios pull request #68
Opened 2023-05-02 09:04 UTC by cb-gadagoju

**Bug Description:**
For one-time Purchases on the failure of purchases the wrong handler is invoked

**Root Cause:** 
we have both subscriptions and non-subscriptions then for Non-subscriptions , subscriptions handler is invoked for one-time purchases also i.e **buyProductHandler** 

**Solution:**
 so updated with the correct handler **buyNonSubscriptionProductHandler**

2023-05-02 12:30 UTC, cb-haripriyan requested changes

2023-05-02 12:36 UTC, cb-haripriyan commented
Fixes: https://github.com/chargebee/chargebee-ios/issues/67

2023-05-05 09:03 UTC, cb-gadagoju commented on Chargebee/Classes/Purchase/CBPurchaseManager.swift
> +                        }
HI @cb-haripriyan  Re-factored the failure block 
done.

2023-05-05 09:37 UTC, cb-haripriyan commented on Chargebee/Classes/Purchase/CBPurchaseManager.swift
>                      print(error)
use `debugPrint` here

2023-05-05 09:41 UTC, cb-haripriyan commented on Chargebee/Classes/Purchase/CBPurchaseManager.swift
> +                        self.invokeProductHandler(forProduct: self.activeProduct?.product, error: CBPurchaseError.productsNotFound)
Any reason why this has been changed?

2023-05-08 11:01 UTC, merged